In [3]:
import pandas as pd
import numpy as np

In [2]:
!  python --version

Python 3.9.12


# 1. Some subroutines

In [3]:
mydata = pd.read_csv('~/Downloads/new_train.csv')
mydata.head()

age           job   marital          education  default housing loan  \
0   49   blue-collar   married           basic.9y  unknown      no   no   
1   37  entrepreneur   married  university.degree       no      no   no   
2   78       retired   married           basic.4y       no      no   no   
3   36        admin.   married  university.degree       no     yes   no   
4   59       retired  divorced  university.degree       no      no   no   

     contact month day_of_week  duration  campaign  pdays  previous  \
0   cellular   nov         wed       227         4    999         0   
1  telephone   nov         wed       202         2    999         1   
2   cellular   jul         mon      1148         1    999         0   
3  telephone   may         mon       120         2    999         0   
4   cellular   jun         tue       368         2    999         0   

      poutcome    y  
0  nonexistent   no  
1      failure   no  
2  nonexistent  yes  
3  nonexistent   no  
4  nonexistent   no

In [4]:
print(set(mydata.job))
print(set(mydata.marital))
print(set(mydata.education))
print(set(mydata.default))
print(set(mydata.housing))
print(set(mydata.loan))
print(set(mydata.contact))
print(set(mydata.month))
print(set(mydata.day_of_week))
print(set(mydata.poutcome))

{'admin.', 'student', 'unemployed', 'self-employed', 'housemaid', 'entrepreneur', 'technician', 'services', 'unknown', 'retired', 'blue-collar', 'management'}
{'divorced', 'married', 'single', 'unknown'}
{'basic.9y', 'basic.4y', 'illiterate', 'high.school', 'university.degree', 'unknown', 'basic.6y', 'professional.course'}
{'yes', 'unknown', 'no'}
{'yes', 'unknown', 'no'}
{'yes', 'unknown', 'no'}
{'telephone', 'cellular'}
{'jul', 'aug', 'apr', 'sep', 'jun', 'oct', 'dec', 'mar', 'may', 'nov'}
{'mon', 'tue', 'thu', 'fri', 'wed'}
{'failure', 'success', 'nonexistent'}


In [5]:
def get_banking():
    mydata = pd.read_csv('~/Downloads/new_train.csv')
    mydata= mydata[['age', 'marital', 'duration', 'campaign', 'pdays', 'previous', 'y']]
    
    mydata['y'] = mydata['y'].map(lambda x: 0 if x == "no" else 1)
    mydata['marital'] = mydata['marital'].map(lambda x: 0 if x == "divorced" else(1 if x == "married" else(2 if x == "single" else 3)))
    mydata.rename({'y': 'label'}, axis = 1, inplace = True)
    
    X = mydata.drop(columns=['label']).values

    from sklearn.preprocessing import StandardScaler
    ss = StandardScaler()
    X = ss.fit_transform(X)
    
    
    y = mydata['label'].values
    return X, y

In [10]:
def corr():
    mdc = pd.read_csv('~/Downloads/new_train.csv')
    mdc['y'] = mdc['y'].map(lambda x: 0 if x == "no" else 1)
    mdc.rename({'y': 'label'}, axis = 1, inplace = True)
    mdc = pd.get_dummies(mdc)
    
#     cols = mdc.columns
#     mdc = mdc[['label'] + list(cols[:-1])]
#     x = mydata.values
#     from sklearn.preprocessing import StandardScaler
#     ss = StandardScaler()
#     x = ss.fit_transform(x)
    return mdc.corr(method = 'pearson')

In [11]:
corr()

age  duration  campaign     pdays  \
age                            1.000000 -0.001841  0.003302 -0.032011   
duration                      -0.001841  1.000000 -0.075663 -0.047127   
campaign                       0.003302 -0.075663  1.000000  0.053795   
pdays                         -0.032011 -0.047127  0.053795  1.000000   
previous                       0.020670  0.022538 -0.079051 -0.589601   
label                          0.028673  0.400752 -0.065462 -0.325539   
job_admin.                    -0.101707 -0.012554  0.012113 -0.022377   
job_blue-collar               -0.020707  0.017492 -0.000804  0.065148   
job_entrepreneur               0.029657  0.007525 -0.004446  0.018408   
job_housemaid                  0.084222 -0.003448  0.005319 -0.003220   
job_management                 0.062914 -0.003474 -0.008690  0.001382   
job_retired                    0.436323  0.012348 -0.005465 -0.067739   
job_self-employed             -0.000788  0.009874  0.006380  0.013277   
job_services                  -0.067384 -0.003981  0.003625  0.029734   
job_student                   -0.200910  0.010701 -0.024102 -0.098745   
job_technician                -0.064355 -0.013590 -0.001021  0.004330   
job_unemployed                -0.002776 -0.006811 -0.001389 -0.029555   
job_unknown                    0.048705 -0.003810  0.002770 -0.012861   
marital_divorced               0.166300 -0.008856  0.004861  0.015136   
marital_married                0.272555 -0.002555 -0.002229  0.032579   
marital_single                -0.412980  0.007807 -0.001976 -0.045463   
marital_unknown                0.001386  0.011884  0.010080 -0.005704   
education_basic.4y             0.245244  0.011121  0.007276  0.006697   
education_basic.6y             0.006321  0.005871  0.000881  0.024546   
education_basic.9y            -0.038201  0.005232 -0.004912  0.039730   
education_high.school         -0.108766  0.004343 -0.004120  0.004076   
education_illiterate           0.013476  0.003064 -0.002487  0.004333   
education_professional.course  0.005435 -0.007956  0.003009 -0.007172   
education_university.degree   -0.067329 -0.013122 -0.000171 -0.035145   
education_unknown              0.062664  0.000924  0.001031 -0.025424   
default_no                    -0.169038  0.010584 -0.037495 -0.081514   
default_unknown                0.169015 -0.010452  0.037600  0.081483   
default_yes                    0.002127 -0.005704 -0.004255  0.001876   
housing_no                     0.002601  0.010150  0.013757  0.012398   
housing_unknown                0.001801 -0.003893 -0.001741  0.004829   
housing_yes                   -0.003145 -0.008918 -0.013174 -0.013840   
loan_no                        0.003466 -0.002354 -0.004824 -0.004001   
loan_unknown                   0.001801 -0.003893 -0.001741  0.004829   
loan_yes                      -0.004446  0.004160  0.005861  0.002182   
contact_cellular              -0.007760  0.026148 -0.074217 -0.116561   
contact_telephone              0.007760 -0.026148  0.074217  0.116561   
month_apr                      0.015919  0.034950 -0.057152 -0.016132   
month_aug                      0.065991 -0.038221  0.015314  0.000053   
month_dec                      0.043224  0.028119 -0.009590 -0.082133   
month_jul                     -0.043805  0.025686  0.095012  0.048396   
month_jun                     -0.006964 -0.022687  0.069209  0.018148   
month_mar                      0.012097 -0.006992 -0.010656 -0.078193   
month_may                     -0.068544  0.003415 -0.032397  0.075357   
month_nov                      0.030311 -0.013431 -0.077970 -0.017506   
month_oct                      0.048997  0.020744 -0.049356 -0.131064   
month_sep                      0.034747  0.013565 -0.032953 -0.162957   
day_of_week_fri                0.009244 -0.011806  0.025339  0.010691   
day_of_week_mon                0.018570 -0.023178  0.012448  0.000200   
day_of_week_thu               -0.021298  0.014738  0.006109 -0.009419   
day_of_week_tue      

In [8]:
def evaluate(pred, expect) :
    ans = pred - expect
    error_sum = ans.sum()
    n_errors = abs(ans).sum()
    accuracy = 1 - n_errors / expect.shape[0]
    
    return round(accuracy, 3) , n_errors, error_sum

In [9]:
def evaluateConfusion(pred, expect):
    ConfusionMatrix = confusion_matrix(expect, pred)
    f1 = f1_score(expect, pred)
    accuracy = accuracy_score(expect, pred)
    recall = recall_score(expect, pred)
    precision = precision_score(expect, pred)
    
    return f1, accuracy, recall,  precision, ConfusionMatrix

# 2. get dataset

In [10]:
X, y= get_banking()   # X: feature vector, y label

# 3. Split Data into Training and Testing
--------
Choose 3.1  and 3.2 to get the type of split data you want to train.

# 3.1 Original Data Split

In [11]:
from sklearn.model_selection import train_test_split

print(X.shape)
print(y.shape)
print(type(X))
print(type(y))
# numpy array does not have column names.  
# We can only use the slice [row_start:row_end:step_row, col_start:col_end:step_col]
# to select rows and cols we want
# be aware that row_end and col_end are not inclusive
# the format of the output will be discussed in another lecture.
print(X[0:6:2])
print(y[0:40:4])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=2018) 


(32950, 6)
(32950,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[ 0.86373877 -0.28487114 -0.12019627  0.52298128  0.19658384 -0.35012691]
 [ 3.65126795 -0.28487114  3.43617293 -0.56702251  0.19658384 -0.35012691]
 [ 1.82495573 -1.9281667   0.42426417 -0.20368791  0.19658384 -0.35012691]]
[0 0 0 0 0 0 1 0 0 0]


# 4. Collect results with various labelratio

# 5. Confusing Matrix

In [12]:
#Accuracy = (TN+TP)/ALL
#Recall = TP/(TP+FN)
#Precision = TP/(TP+FP)
#F1 Score = 2*(Precision*Recall)/(Precision+Recall)

In [13]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, recall_score, precision_score

In [14]:
def RunAllConfusion(X_train, X_test, y_train, y_test, default = 1) :
    
    # default: 1 for default class_weight (or default weights if KNN)
    # default: 0 forclass_weight = balanced (or weights = 'distance' if KNN)
    
    results = []
    
    from sklearn.tree import DecisionTreeClassifier
    if default :
        DT = DecisionTreeClassifier()
    else:
        DT = DecisionTreeClassifier(class_weight='balanced') # default:None, other: balanced
    model = DT
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    results = results + [['DT'] + list( evaluateConfusion(pred, y_test))]
    

    from sklearn.ensemble import RandomForestClassifier
    if default :
        RF = RandomForestClassifier(n_estimators =50)
    else:
        RF = RandomForestClassifier(n_estimators =50, class_weight='balanced') # default:None, other: balanced    
    model = RF
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    results = results + [['RF'] + list( evaluateConfusion(pred, y_test))]
    
        
    from sklearn.neighbors import KNeighborsClassifier
    if default :
        KNN = KNeighborsClassifier()
    else:
        KNN = KNeighborsClassifier(weights = 'distance') # default:uniform, other: distance    
    model = KNN
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    results = results + [['KNN'] + list( evaluateConfusion(pred, y_test))]
    
        
    from sklearn.svm import SVC
    if default :
        SVM = SVC(gamma='scale')
    else:
        SVM = SVC(gamma='scale', class_weight='balanced') # default:None, other: balanced
    model = SVM
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    results = results + [['SVM'] + list( evaluateConfusion(pred, y_test))]
    
    
    from sklearn.linear_model import LogisticRegression
    if default :
        LogR = LogisticRegression()
    else:
        LogR = LogisticRegression(class_weight='balanced') # default:None, other: balanced
    model = LogR
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    results = results + [['LogR'] + list( evaluateConfusion(pred, y_test))]
    
    
    return results


In [15]:
Default = RunAllConfusion(X_train, X_test, y_train, y_test, default = 1)

In [16]:
Weight = RunAllConfusion(X_train, X_test, y_train, y_test, default = 0)

In [17]:
DefaultDF = pd.DataFrame(Default, columns = ['method', 'f1', 'accuracy', 'recall',  'precision', 'ConfusionMatrix'])
WeightDF = pd.DataFrame(Weight, columns = ['method', 'f1', 'accuracy', 'recall',  'precision', 'ConfusionMatrix'])

In [18]:
DefaultDF.head()

method        f1  accuracy    recall  precision            ConfusionMatrix
0     DT  0.395568  0.867565  0.392739   0.398438  [[6790, 539], [552, 357]]
1     RF  0.459987  0.895970  0.401540   0.538348  [[7016, 313], [544, 365]]
2    KNN  0.462549  0.900704  0.387239   0.574225  [[7068, 261], [557, 352]]
3    SVM  0.416667  0.906531  0.302530   0.669100  [[7193, 136], [634, 275]]
4   LogR  0.443950  0.909080  0.328933   0.682648  [[7190, 139], [610, 299]]

In [19]:
WeightDF.head()

method        f1  accuracy    recall  precision             ConfusionMatrix
0     DT  0.398898  0.867565  0.398240   0.399558   [[6785, 544], [547, 362]]
1     RF  0.448875  0.895970  0.383938   0.540248   [[7032, 297], [560, 349]]
2    KNN  0.444717  0.890265  0.398240   0.503477   [[6972, 357], [547, 362]]
3    SVM  0.498597  0.826414  0.782178   0.365929  [[6097, 1232], [198, 711]]
4   LogR  0.498660  0.841102  0.716172   0.382491  [[6278, 1051], [258, 651]]