In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import time

In [2]:
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense

# 1. Get data

In [5]:
def get_bcw():
    bcw = pd.read_csv(r"C:\Users\user\Downloads\wdbc.data")
    names = ['id','malignant',
         'nucleus_mean','nucleus_se','nucleus_worst',
         'texture_mean','texture_se','texture_worst',
         'perimeter_mean','perimeter_se','perimeter_worst',
         'area_mean','area_se','area_worst',
         'smoothness_mean','smoothness_se','smoothness_worst',
         'compactness_mean','compactness_se','compactness_worst',
         'concavity_mean','concavity_se','concavity_worst',
         'concave points_mean','concave points_se','concave points_worst',
         'symmetry_mean','symmetry_se','symmetry_worst',
         'fractal_dimension_mean','fractal_dimension_se','fractal_dimension_worst']
    bcw.columns = names
    bcw['malignant'] = bcw['malignant'].map(lambda x: 0 if x == "B" else 1)
    
    y = bcw['malignant'].values
    X = bcw.drop(columns = ['id','malignant']).values
#     from sklearn.preprocessing import StandardScaler
#     ss = StandardScaler()
#     X = ss.fit_transform(X)
#     print(X)
#     plt.scatter(X[:, 0], X[:, 1], c = y)
    
    return X, y

In [6]:
X, y = get_bcw()

In [7]:
Nclasses = len(set(y))
Nclasses

2

# 2. Split data into Training and Testing

In [8]:
from sklearn.model_selection import train_test_split

print(X.shape)
print(y.shape)
print(type(X))
print(type(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 2018)

(568, 30)
(568,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(284, 30)
(284, 30)
(284,)
(284,)


In [10]:
X_train[:20:6]

array([[1.425e+01, 2.172e+01, 9.363e+01, 6.330e+02, 9.823e-02, 1.098e-01,
        1.319e-01, 5.598e-02, 1.885e-01, 6.125e-02, 2.860e-01, 1.019e+00,
        2.657e+00, 2.491e+01, 5.878e-03, 2.995e-02, 4.815e-02, 1.161e-02,
        2.028e-02, 4.022e-03, 1.589e+01, 3.036e+01, 1.162e+02, 7.996e+02,
        1.446e-01, 4.238e-01, 5.186e-01, 1.447e-01, 3.591e-01, 1.014e-01],
       [1.537e+01, 2.276e+01, 1.002e+02, 7.282e+02, 9.200e-02, 1.036e-01,
        1.122e-01, 7.483e-02, 1.717e-01, 6.097e-02, 3.129e-01, 8.413e-01,
        2.075e+00, 2.944e+01, 9.882e-03, 2.444e-02, 4.531e-02, 1.763e-02,
        2.471e-02, 2.142e-03, 1.643e+01, 2.584e+01, 1.075e+02, 8.309e+02,
        1.257e-01, 1.997e-01, 2.846e-01, 1.476e-01, 2.556e-01, 6.828e-02],
       [1.193e+01, 2.153e+01, 7.653e+01, 4.386e+02, 9.768e-02, 7.849e-02,
        3.328e-02, 2.008e-02, 1.688e-01, 6.194e-02, 3.118e-01, 9.227e-01,
        2.000e+00, 2.479e+01, 7.803e-03, 2.507e-02, 1.835e-02, 7.711e-03,
        1.278e-02, 3.856e-03, 1.367e

## Convert scalar class into vector class for NN

In [11]:
Y_train = np_utils.to_categorical(y_train)
Y_test = np_utils.to_categorical(y_test)

In [12]:
print(X_train.shape)

print(Y_train.shape)

(284, 30)
(284, 2)


# 3. Build ML/DL Model

In [13]:
model = Sequential()
N_Features = X_train.shape[1]

model.add(Dense(N_Features, activation = 'relu'))
model.add(Dense(Nclasses, activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# 4. Training

In [14]:
start = time.time()
model.fit(X_train, Y_train, epochs = 10, verbose = 1)
print('duration =', time.time() - start)

Epoch 1/10
9/9 [==============================] - 0s 1ms/step - loss: 18.3658 - accuracy: 0.3028
Epoch 2/10
9/9 [==============================] - 0s 659us/step - loss: 11.7126 - accuracy: 0.2887
Epoch 3/10
9/9 [==============================] - 0s 1ms/step - loss: 9.6749 - accuracy: 0.2923
Epoch 4/10
9/9 [==============================] - 0s 6ms/step - loss: 8.1755 - accuracy: 0.2641
Epoch 5/10
9/9 [==============================] - 0s 1ms/step - loss: 6.6540 - accuracy: 0.3451
Epoch 6/10
9/9 [==============================] - 0s 949us/step - loss: 5.2034 - accuracy: 0.3732
Epoch 7/10
9/9 [==============================] - 0s 544us/step - loss: 4.4645 - accuracy: 0.3908
Epoch 8/10
9/9 [==============================] - 0s 780us/step - loss: 3.2005 - accuracy: 0.4648
Epoch 9/10
9/9 [==============================] - 0s 1ms/step - loss: 2.1204 - accuracy: 0.5739
Epoch 10/10
9/9 [==============================] - 0s 758us/step - loss: 1.2753 - accuracy: 0.6655
duration = 0.61667180061340

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                930       
                                                                 
 dense_1 (Dense)             (None, 2)                 62        
                                                                 
Total params: 992
Trainable params: 992
Non-trainable params: 0
_________________________________________________________________


# 5. Testing

In [16]:
pred = model.predict(X_test)

9/9 [==============================] - 0s 717us/step


In [17]:
pred[3].sum()

1.0

In [18]:
pred[80].sum()

0.99999994

In [19]:
pred[:30]

array([[9.9933606e-01, 6.6393428e-04],
       [5.4438761e-03, 9.9455607e-01],
       [9.9979526e-01, 2.0479377e-04],
       [9.9983025e-01, 1.6976149e-04],
       [3.5816985e-11, 1.0000000e+00],
       [4.9236176e-05, 9.9995077e-01],
       [9.9982786e-01, 1.7211703e-04],
       [5.0273840e-04, 9.9949729e-01],
       [1.6790389e-10, 1.0000000e+00],
       [2.7744995e-10, 1.0000000e+00],
       [7.7041059e-06, 9.9999225e-01],
       [9.9999928e-01, 7.3785259e-07],
       [6.9727915e-13, 1.0000000e+00],
       [9.9999988e-01, 8.6375259e-08],
       [4.6593988e-01, 5.3406012e-01],
       [1.1823091e-01, 8.8176912e-01],
       [9.7786158e-01, 2.2138391e-02],
       [1.0000000e+00, 1.4666824e-08],
       [9.9996364e-01, 3.6412850e-05],
       [9.9781162e-01, 2.1884213e-03],
       [9.8984247e-01, 1.0157594e-02],
       [1.4044175e-11, 1.0000000e+00],
       [3.5227035e-04, 9.9964774e-01],
       [9.9966443e-01, 3.3563114e-04],
       [9.9932456e-01, 6.7544205e-04],
       [2.3155364e-01, 7.

# 6. Evaluate the Result

In [20]:
tmp = np.array([int(x < y) for [x, y] in pred])
tmp

array([0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1])

In [21]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1],
      dtype=int64)

In [22]:
1 - abs(tmp - y_test).sum() / y_test.shape[0]

0.7640845070422535