In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import r2_score, mean_squared_error
from sklearn.preprocessing import StandardScaler

## Read data

In [2]:
df = pd.read_csv("D:\Downloads\clean_train.csv")
print(df.shape)
print(df.head())

(1456, 81)
   Id     MSSubClass MSZoning  LotFrontage  LotArea Street Alley  LotShape  \
0   1  2-STORY 1946+       RL         65.0     8450   Pave   NaN         0   
1   2  1-STORY 1946+       RL         80.0     9600   Pave   NaN         0   
2   3  2-STORY 1946+       RL         68.0    11250   Pave   NaN         1   
3   4  2-STORY 1945-       RL         60.0     9550   Pave   NaN         1   
4   5  2-STORY 1946+       RL         84.0    14260   Pave   NaN         1   

  LandContour  Utilities  ... PoolArea  PoolQC Fence MiscFeature MiscVal  \
0         Lvl          3  ...        0       0     0         NaN       0   
1         Lvl          3  ...        0       0     0         NaN       0   
2         Lvl          3  ...        0       0     0         NaN       0   
3         Lvl          3  ...        0       0     0         NaN       0   
4         Lvl          3  ...        0       0     0         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0    Feb 

## Find missing values

#### if appropriate , remove the columns with missing values

In [3]:
a = df.isnull().sum().reset_index()
a.columns = ['names', 'missingcount']
# print(a.head())
print(a[a['missingcount'] != 0])

          names  missingcount
3   LotFrontage           259
6         Alley          1365
58   GarageType            81
74  MiscFeature          1403


In [4]:
a[a['missingcount'] != 0].names

3     LotFrontage
6           Alley
58     GarageType
74    MiscFeature
Name: names, dtype: object

In [5]:
df.shape

(1456, 81)

In [6]:
df1 = df.drop(a[a['missingcount'] != 0].names, axis=1)
df1.shape

(1456, 77)

## Remove columns of object type

In [9]:
a = df1.dtypes.reset_index()
a.columns = ['names', 'type']
print(a.head())
numerical_columns = list(a[a.type != 'object'].names)
print(numerical_columns)

        names    type
0          Id   int64
1  MSSubClass  object
2    MSZoning  object
3     LotArea   int64
4      Street  object
['Id', 'LotArea', 'LotShape', 'Utilities', 'LandSlope', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'ExterQual', 'ExterCond', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscVal', 'YrSold', 'SalePrice']


In [10]:
df2 = df1[numerical_columns]
print(df1.shape)
print(df2.head(), '\n', df2.shape)

(1456, 77)
   Id  LotArea  LotShape  Utilities  LandSlope  OverallQual  OverallCond  \
0   1     8450         0          3          0            7            5   
1   2     9600         0          3          0            6            8   
2   3    11250         1          3          0            7            5   
3   4     9550         1          3          0            7            5   
4   5    14260         1          3          0            8            5   

   YearBuilt  YearRemodAdd  MasVnrArea  ...  OpenPorchSF  EnclosedPorch  \
0       2003          2003       196.0  ...           61              0   
1       1976          1976         0.0  ...            0              0   
2       2001          2002       162.0  ...           42              0   
3       1915          1970         0.0  ...           35            272   
4       2000          2000       350.0  ...           84              0   

   3SsnPorch  ScreenPorch  PoolArea  PoolQC  Fence  MiscVal  YrSold  SalePrice  


In [12]:
df2.isna().sum().sum()

0

## Prepare training and testing data

In [13]:
y_train = df2.SalePrice.values
X_train = df2.drop('SalePrice', axis=1).values
print(X_train.shape, y_train)

(1456, 56) [208500 181500 223500 ... 266500 142125 147500]


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size = 0.5, random_state=2018)

## Try ML models for classification

In [32]:
# model = DecisionTreeClassifier()
# model = RandomForestClassifier()
# model = KNeighborsClassifier()
# model = SVC()
model = LogisticRegression()

model.fit(X_train, y_train)
pred_test = model.predict(X_test)
pred_train = model.predict(X_train)
print(r2_score(y_train, pred_train), r2_score(y_test, pred_test))

0.5935052844682418 0.4584365449585741


D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [33]:
jjj = (pred_train == y_test).sum()
print(jjj, jjj/len(pred_train))

4 0.005494505494505495


In [34]:
jjj = (pred_test == y_train).sum()
print(jjj, jjj/len(pred_test))

4 0.005494505494505495


In [35]:
print(pred_test[:10])
print(y_test[:10])

[254000 145000 315000 150000 260000 122500 190000  84500 215000 290000]
[190000 163500 377426 214000 223500 145000 172500 148000 175000 383970]


## Classification can not take continuous values as label

#### How about if we change y_train to type float, wouldn't it work in classification

In [41]:
# y_train_float = y_train.astype('float')
y_train_float = y_train * 1.0001
print(type(y_train_float[0]))
print(y_train_float[0:5])
print(y_train[0:5])

<class 'numpy.float64'>
[190019.  127012.7 147014.7 125012.5 195019.5]
[190000 127000 147000 125000 195000]


In [44]:
model = DecisionTreeClassifier()
# model = RandomForestClassifier()
# model = KNeighborsClassifier()
# model = SVC()
# model = LogisticRegression()

model.fit(X_train, y_train)
pred_test = model.predict(X_test)
pred_train = model.predict(X_train)
print(r2_score(y_train, pred_train), r2_score(y_test, pred_test))

1.0 0.5823704004634687
